<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-11T15:29:48 IST" name="Suite" finished-at="2023-07-11T15:30:15 IST" duration-ms="27322">
    <groups>
    </groups>
    <test started-at="2023-07-11T15:29:48 IST" name="TestChrome" finished-at="2023-07-11T15:30:02 IST" duration-ms="14094">
      <class name="org.hcl.tests.SSLTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:org.hcl.tests.SSLTest@41fbdac4]" started-at="2023-07-11T15:29:48 IST" name="setup" finished-at="2023-07-11T15:29:57 IST" duration-ms="9161" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySSL(java.lang.String)[pri:0, instance:org.hcl.tests.SSLTest@41fbdac4]" started-at="2023-07-11T15:29:57 IST" name="verifySSL" finished-at="2023-07-11T15:30:01 IST" duration-ms="4177" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Your connection is not private]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
title not matching.... expected [Privacy error] but found [Welcome to CAcert.org]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
title not matching.... expected [Privacy error] but found [Welcome to CAcert.org]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at org.hcl.tests.SSLTest.verifySSL(SSLTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySSL -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.hcl.tests.SSLTest@41fbdac4]" started-at="2023-07-11T15:30:01 IST" name="tearDown" finished-at="2023-07-11T15:30:02 IST" duration-ms="724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.hcl.tests.SSLTest -->
    </test> <!-- TestChrome -->
    <test started-at="2023-07-11T15:30:02 IST" name="TestEdge" finished-at="2023-07-11T15:30:15 IST" duration-ms="13089">
      <class name="org.hcl.tests.SSLTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:org.hcl.tests.SSLTest@2d7275fc]" started-at="2023-07-11T15:30:02 IST" name="setup" finished-at="2023-07-11T15:30:12 IST" duration-ms="9849" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySSL(java.lang.String)[pri:0, instance:org.hcl.tests.SSLTest@2d7275fc]" started-at="2023-07-11T15:30:12 IST" name="verifySSL" finished-at="2023-07-11T15:30:14 IST" duration-ms="2595" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Your connection isn't private]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
title not matching.... expected [Privacy error] but found [Welcome to CAcert.org]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
title not matching.... expected [Privacy error] but found [Welcome to CAcert.org]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at org.hcl.tests.SSLTest.verifySSL(SSLTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySSL -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.hcl.tests.SSLTest@2d7275fc]" started-at="2023-07-11T15:30:14 IST" name="tearDown" finished-at="2023-07-11T15:30:15 IST" duration-ms="639" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.hcl.tests.SSLTest -->
    </test> <!-- TestEdge -->
  </suite> <!-- Suite -->
</testng-results>
